<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scghi -O1 -gl -vewnhi -l -Fu.;mui;../units/%(CPU_TARGET)-%(OS_TARGET);../../packager/units/%(CPU_TARGET)-%(OS_TARGET) -Fimui lcl.pas"/>
</CONFIG>
