{ This is an autogenerated unit using gobject introspection (gir2pascal). Do not Edit. }
unit Lazfreetype2_2;

{$MODE OBJFPC}{$H+}

{$PACKRECORDS C}
{$MODESWITCH DUPLICATELOCALS+}

{$ifdef Unix}
{$endif}
interface
uses
  CTypes;

const
  {$ifdef MsWindows}
  Lazfreetype2_2_library = '.dll';
  {$else}
  Lazfreetype2_2_library = '';
  {$endif}

type


  { TFT_Bitmap }
  PPFT_Bitmap = ^PFT_Bitmap;
  PFT_Bitmap = ^TFT_Bitmap;

  TFT_Bitmap = record
  end;




  { TFT_Face }
  PPFT_Face = ^PFT_Face;
  PFT_Face = ^TFT_Face;

  TFT_Face = record
  end;




  { TFT_Library }
  PPFT_Library = ^PFT_Library;
  PFT_Library = ^TFT_Library;

  TFT_Library = record
  end;



implementation
end.