<?xml version="1.0" encoding="UTF-8"?>
<CONFIG>
  <Makefile Value="2"/>
  <Params Value=" -Fu../../../packager/units/$(CPU_TARGET)-$(OS_TARGET);../../lazutils/lib/$(CPU_TARGET)-$(OS_TARGET);../../buildintf/units/$(CPU_TARGET)-$(OS_TARGET);../../freetype/lib/$(CPU_TARGET)-$(OS_TARGET);../../../lcl/units/$(CPU_TARGET)-$(OS_TARGET);../../debuggerintf/lib/$(CPU_TARGET)-$(OS_TARGET);../../../lcl/units/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);../../fpdebug/lib/$(CPU_TARGET)-$(OS_TARGET);../../lazcontrols/lib/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);../../ideintf/units/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);../cmdlinedebuggerbase/lib/$(CPU_TARGET)-$(OS_TARGET);.  -MObjFPC -Scghi -O1 -g -gl -l -vewnhibq -vm6058,3123 -dLCL -dLCL$(LCL_PLATFORM) -O-1 -Si -Sa -gh -gtt -CR- -Criot -gw2 -godwarfsets -gl lazdebuggerfp.pas"/>
</CONFIG>
