{
   File generated automatically by Lazarus Package Manager

   fpmake.pp for LCL 2.1

   This file was generated on 29-12-18
}

{$ifndef ALLPACKAGES} 
{$mode objfpc}{$H+}
program fpmake;

uses fpmkunit;
{$endif ALLPACKAGES}

procedure add_LCL(const ADirectory: string);

var
  P : TPackage;
  T : TTarget;

var
  LCLWidgetTypeVariant: TPackageVariants;
  carbonVariantItem, gtkVariantItem, gtk2VariantItem, win32VariantItem, winceVariantItem, cocoaVariantItem, fpguiVariantItem, noguiVariantItem, qt5VariantItem, qtVariantItem, customdrawnVariantItem, gtk3VariantItem: TPackageVariant;
begin
  with Installer do
    begin
    P:=AddPackage('lcl');
    P.Version:='2.1';

    P.Directory:=ADirectory;

    P.Flags.Add('LazarusDsgnPkg');

    P.Dependencies.Add('lclbase');
    P.Options.Add('-MObjFPC');
    P.Options.Add('-Scghi');
    P.Options.Add('-O1');
    P.Options.Add('-g');
    P.Options.Add('-gl');
    P.Options.Add('-l');
    P.Options.Add('-vewnhibq');
    P.Options.Add('-vm5044');
    P.IncludePath.Add('$(LCLWidgetType)');
    P.UnitPath.Add('$(LCLWidgetType)');
    P.UnitPath.Add('.');
    LCLWidgetTypeVariant := AddPackageVariant('LCLWidgetType',true);
    P.AddPackageVariant(LCLWidgetTypeVariant);
    carbonVariantItem := LCLWidgetTypeVariant.add('carbon');
    gtkVariantItem := LCLWidgetTypeVariant.add('gtk');
    gtkVariantItem.Options.Add('-dgtk1');
    gtk2VariantItem := LCLWidgetTypeVariant.add('gtk2');
    win32VariantItem := LCLWidgetTypeVariant.add('win32');
    winceVariantItem := LCLWidgetTypeVariant.add('wince');
    cocoaVariantItem := LCLWidgetTypeVariant.add('cocoa');
    fpguiVariantItem := LCLWidgetTypeVariant.add('fpgui');
    noguiVariantItem := LCLWidgetTypeVariant.add('nogui');
    qt5VariantItem := LCLWidgetTypeVariant.add('qt5');
    qtVariantItem := LCLWidgetTypeVariant.add('qt');
    customdrawnVariantItem := LCLWidgetTypeVariant.add('customdrawn');
    gtk3VariantItem := LCLWidgetTypeVariant.add('gtk3');
case Defaults.OS of
  darwin        : LCLWidgetTypeVariant.DefaultPackageVariantName:='carbon';
  win32, win64  : LCLWidgetTypeVariant.DefaultPackageVariantName:='win32';
  wince         : LCLWidgetTypeVariant.DefaultPackageVariantName:='wince';
else
  LCLWidgetTypeVariant.DefaultPackageVariantName:='gtk2';
end;
P.Dependencies.Add('gtk2', AllUnixOSes+[Win32,Win64]-[darwin,iphonesim,Android]);
gtk3VariantItem.IncludePath.add('gtk3/gtk3bindings');
    T:=P.Targets.AddUnit('lcl.pas');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/agl.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/alllclintfunits.pas');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonbars.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonbuttons.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carboncalendar.pas');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carboncalendarview.pas');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carboncanvas.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carboncaret.pas');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonclipboard.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbondbgconsts.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbondebug.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbondef.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonedits.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbongdiobjects.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonint.pas');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonlistviews.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonmenus.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonprivate.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonproc.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonstrings.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbontabs.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonthemes.pas');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonutils.pas');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwsbuttons.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwscalendar.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwschecklst.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwscomctrls.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwscontrols.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwsdialogs.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwsextctrls.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwsextdlgs.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwsfactory.pas');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwsforms.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwsgrids.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwsimglist.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwsmenus.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwspairsplitter.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwsspin.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/carbonwsstdctrls.pp');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/glgrab.pas');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/interfaces.pas');
    carbonVariantItem.Targets.AddImplicitUnit('carbon/opengl.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/alllclintfunits.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoagdiobjects.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoaint.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoaprivate.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoautils.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoawscommon.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoawsextctrls.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoawsfactory.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoawsforms.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoawsmenus.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoawsstdctrls.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/interfaces.pas');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/alllclintfunits.pas');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiint.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiobjects.pas');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiproc.pas');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwsbuttons.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwscalendar.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwscomctrls.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwscontrols.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwsdialogs.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwsextctrls.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwsextdlgs.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwsfactory.pas');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwsforms.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwsgrids.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwsimglist.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwsmenus.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwspairsplitter.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwsprivate.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/fpguiwsstdctrls.pp');
    fpguiVariantItem.Targets.AddImplicitUnit('fpgui/interfaces.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/alllclintfunits.pas');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtk1def.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtk1int.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtk1wsprivate.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkdebug.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkdef.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkextra.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkfontcache.pas');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkglobals.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkint.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkmsgqueue.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkproc.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkthemes.pas');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwinapiwindow.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwsbuttons.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwscalendar.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwschecklst.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwscomctrls.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwscontrols.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwsdialogs.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwsextctrls.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwsextdlgs.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwsfactory.pas');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwsforms.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwsgrids.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwsimglist.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwsmenus.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwspairsplitter.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwsprivate.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwsspin.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/gtkwsstdctrls.pp');
    gtkVariantItem.Targets.AddImplicitUnit('gtk/interfaces.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/alllclintfunits.pas');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2cellrenderer.pas');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2debug.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2def.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2extra.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2fontcache.pas');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2globals.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2int.pas');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2listviewtreemodel.pas');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2msgqueue.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2proc.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2themes.pas');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2winapiwindow.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2windows.pas');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wsbuttons.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wscalendar.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wschecklst.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wscomctrls.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wscontrols.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wsdialogs.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wsextctrls.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wsextdlgs.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wsfactory.pas');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wsforms.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wsgrids.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wsimglist.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wsmenus.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wspairsplitter.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wsprivate.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wsspin.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2wsstdctrls.pp');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/unitywsctrls.pas');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/interfaces.pas');
    win32VariantItem.Targets.AddImplicitUnit('win32/alllclintfunits.pas');
    win32VariantItem.Targets.AddImplicitUnit('win32/interfaces.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32debug.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32def.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32extra.pas');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32int.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32proc.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32themes.pas');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wsbuttons.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wscalendar.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wschecklst.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wscomctrls.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wscontrols.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wsdialogs.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wsextctrls.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wsextdlgs.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wsfactory.pas');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wsforms.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wsgrids.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wsimglist.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wsmenus.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wspairsplitter.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wsspin.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wsstdctrls.pp');
    win32VariantItem.Targets.AddImplicitUnit('win32/win32wstoolwin.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/interfaces.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/win32compat.pas');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincedef.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/winceextra.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/winceint.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/winceproc.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewsbuttons.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewscalendar.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewschecklst.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewscomctrls.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewscontrols.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewsdialogs.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewsextctrls.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewsfactory.pas');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewsforms.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewsgrids.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewsimglist.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewsmenus.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewsspin.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/wincewsstdctrls.pp');
    winceVariantItem.Targets.AddImplicitUnit('wince/winext.pas');
    winceVariantItem.Targets.AddImplicitUnit('wince/alllclintfunits.pas');
    qtVariantItem.Targets.AddImplicitUnit('qt/alllclintfunits.pas');
    qtVariantItem.Targets.AddImplicitUnit('qt/interfaces.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qt4.pas');
    qtVariantItem.Targets.AddImplicitUnit('qt/qt45.pas');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtcaret.pas');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtint.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtobjects.pas');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtprivate.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtproc.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtthemes.pas');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwidgets.pas');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwsbuttons.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwscalendar.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwschecklst.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwscomctrls.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwscontrols.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwsdesigner.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwsdialogs.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwsextctrls.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwsextdlgs.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwsfactory.pas');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwsforms.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwsgrids.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwsimglist.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwsmenus.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwspairsplitter.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwsspin.pp');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtwsstdctrls.pp');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoawsbuttons.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawn_winproc.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/alllclintfunits.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnint.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnwscontrols.pp');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnwsfactory.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnwsforms.pp');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/interfaces.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/cocoagdiobjects.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawn_cocoaproc.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/cocoautils.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnproc.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawn_x11proc.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawn_androidproc.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/android_native_app_glue.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/asset_manager.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/configuration.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/egl.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/gles.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/input.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/jni.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/keycodes.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/log.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/looper.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/native_activity.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/native_window.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/rect.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/android/bitmap.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnwsstdctrls.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnwscomctrls.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnwsextctrls.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnprivate.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoacaret.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnwslazdeviceapis.pas');
    noguiVariantItem.Targets.AddImplicitUnit('nogui/alllclintfunits.pas');
    noguiVariantItem.Targets.AddImplicitUnit('nogui/interfaces.pp');
    noguiVariantItem.Targets.AddImplicitUnit('nogui/noguiint.pp');
    noguiVariantItem.Targets.AddImplicitUnit('nogui/noguiwsfactory.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnwsspin.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnwsbuttons.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnwsdialogs.pas');
    customdrawnVariantItem.Targets.AddImplicitUnit('customdrawn/customdrawnwsmenus.pas');
    gtk2VariantItem.Targets.AddImplicitUnit('gtk2/gtk2disableliboverlay.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3int.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/interfaces.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3cellrenderer.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3objects.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3private.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3procs.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3widgets.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wsbuttons.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wschecklst.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wscomctrls.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wscontrols.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wsextctrls.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wsfactory.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wsforms.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wsimglist.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wsmenus.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wsspin.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wsstdctrls.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wscalendar.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3bindings/lazatk1.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3bindings/lazcairo1.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3bindings/lazgdk3.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3bindings/lazgdkpixbuf2.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3bindings/lazgio2.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3bindings/lazglib2.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3bindings/lazgmodule2.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3bindings/lazgobject2.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3bindings/lazgtk3.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoawsdialogs.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3bindings/lazpango1.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3bindings/lazpangocairo1.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoathemes.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoawscomctrls.pas');
    qtVariantItem.Targets.AddImplicitUnit('qt/qtsystemtrayicon.pas');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wsdialogs.pp');
    gtk3VariantItem.Targets.AddImplicitUnit('gtk3/gtk3wsextdlgs.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/alllclintfunits.pas');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/interfaces.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qt5.pas');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtcaret.pas');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtint.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtobjects.pas');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtprivate.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtproc.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtsystemtrayicon.pas');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtthemes.pas');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwidgets.pas');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwsbuttons.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwscalendar.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwschecklst.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwscomctrls.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwscontrols.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwsdesigner.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwsdialogs.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwsextctrls.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwsextdlgs.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwsfactory.pas');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwsforms.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwsgrids.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwsimglist.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwsmenus.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwspairsplitter.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwsspin.pp');
    qt5VariantItem.Targets.AddImplicitUnit('qt5/qtwsstdctrls.pp');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoatabcontrols.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoabuttons.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoawindows.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoatables.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoatextedits.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoascrollers.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoawsclipboard.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoawschecklst.pas');
    cocoaVariantItem.Targets.AddImplicitUnit('cocoa/cocoadatepicker.pas');

    // copy the compiled file, so the IDE knows how the package was compiled
    P.InstallFiles.Add('LCL.compiled',AllOSes,'$(unitinstalldir)');

    end;
end;

{$ifndef ALLPACKAGES}
begin
  add_LCL('');
  Installer.Run;
end.
{$endif ALLPACKAGES}
