<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Sgi -O1 -g -gl -vewnhi -l -Fu../../../lazarus/components/codetools/units/%(CPU_TARGET)-%(OS_TARGET);../../../lazarus/components/synedit/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../lazarus/ideintf/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../lazarus/components/lazcontrols/lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../lazarus/lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../lazarus/lcl/units/%(CPU_TARGET)-%(OS_TARGET);../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../../../lazarus/packager/units/%(CPU_TARGET)-%(OS_TARGET);. -dLCL -dLCL%(LCL_PLATFORM) lazsvnpkg.pas"/>
</CONFIG>
