<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scghi -CR -O1 -g -gl -vewnh -l -vm4055,5024 -Fu../../../lazarus/ideintf/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../lazarus/components/lazcontrols/lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../lazarus/lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../lazarus/lcl/units/%(CPU_TARGET)-%(OS_TARGET);../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../../../lazarus/packager/units/%(CPU_TARGET)-%(OS_TARGET);. -dLCL -dLCL%(LCL_PLATFORM) -CR -dgc allsynedit.pas"/>
</CONFIG>
