unit LazDebuggerIntfExceptions;

{$mode objfpc}{$H+}
{$INTERFACES CORBA} // no ref counting needed

interface

uses LazDebuggerIntfBaseTypes;

type

  { IDbgExceptionTargetInfo - provided by the debugger back-end
    The interface is only valid while inside a call that received it as parameter

    Back-ends should use the template.
    This interface may get additional methods, which will then have defaults in the template
    - Address and ClassName must be implemented by each backend
  }

  TDbgTargetExceptionKind =(
    tekUnknown,
    tekFpcRaise,
    tekFpcRunError,
    tekSignal,
    tekOther
  );

  IDbgTargetExceptionInfo = interface ['{672B6CF4-16DB-41D4-995A-71FEBEB3C73E}']
    function GetExceptionAddress: TDBGPtr;
    function GetExceptionKind: TDbgTargetExceptionKind;
    (* For exception other than tekFpcRaise the ClassName and Message are generated by the backend *)
    function GetExceptionClassName: String;
    function GetExceptionMessage(out AMessage: String): boolean;
    function GetExceptionRaiseAtFrameAddr(out AFrameAddr: TDBGPtr): boolean;
    (* BaseClassName:
       - AnIndex specifies how many levels of inheritance to walk.
         0 means the current class itself
         Result indicate if the index was in range.
         If the index is 0 then False means the function is not supported
    *)
    function GetExceptionBaseClassName(out AClassName: String; AnIndex: integer): boolean;


    property Address: TDBGPtr read GetExceptionAddress;
    property ClassName: String read GetExceptionClassName;
    property Kind: TDbgTargetExceptionKind read GetExceptionKind;
  end;

  { IDbgExceptionHandler - provided by the debugger front-end }

  IDbgExceptionHandler = interface ['{120E119B-0249-4957-BC7F-4F0521AE35E2}']
    procedure DoExceptionHit(var AContinue: Boolean; out ANeedInternalPause: boolean; const AnExceptTargetInfo: IDbgTargetExceptionInfo);

    function GetExpression: String;
    function GetEnabled: Boolean; deprecated 'use Hit';
    function GetName: String; deprecated 'use Hit';

    property Expression: String read GetExpression;
    property Name: String read GetName; deprecated 'use Hit';
    property Enabled: Boolean read GetEnabled; deprecated 'use Hit'; // ignored if enabled
  end;

  { IDbgExceptionHandlerList - provided by the debugger front-end }

  IDbgExceptionHandlerList = interface ['{D25EE57A-2F56-4718-A080-5C6C2D84DC10}']
    function GetIgnoreAllExceptions: Boolean;
    function FindExceptionHandler(const AnExceptTargetInfo: IDbgTargetExceptionInfo): IDbgExceptionHandler;
    function Find(const AClassName: String): IDbgExceptionHandler; deprecated 'use Find(ExceptInfo)';

    property IgnoreAll: Boolean read GetIgnoreAllExceptions;
  end;

  { TDbgTargetExceptionInfoTemplate }

  generic TDbgTargetExceptionInfoTemplate<_Base: TObject> = class(_Base , IDbgTargetExceptionInfo)
  strict private
    function GetExceptionAddress: TDBGPtr;
    function GetExceptionClassName: String;
  protected
    function GetExceptionKind: TDbgTargetExceptionKind;
    function GetExceptionMessage(out AMessage: String): boolean;
    function GetExceptionRaiseAtFrameAddr(out AFrameAddr: TDBGPtr): boolean;
    function GetExceptionBaseClassName(out AClassName: String; AnIndex: integer): boolean;
  end;

  { TDbgExceptionHandlerListTemplate }

  generic TDbgExceptionHandlerListTemplate<_Base: TObject> = class(_Base, IDbgExceptionHandlerList)
  protected
    function GetIgnoreAllExceptions: Boolean;
    function FindExceptionHandler(const AnExceptTargetInfo: IDbgTargetExceptionInfo): IDbgExceptionHandler;
    function Find(const AClassName: String): IDbgExceptionHandler; deprecated 'use Find(ExceptInfo)';

    property IgnoreAll: Boolean read GetIgnoreAllExceptions;
  end;

implementation

{ TDbgTargetExceptionInfoTemplate }

function TDbgTargetExceptionInfoTemplate.GetExceptionAddress: TDBGPtr;
begin
  Result := 0;
end;

function TDbgTargetExceptionInfoTemplate.GetExceptionClassName: String;
begin
  Result := '';
end;

function TDbgTargetExceptionInfoTemplate.GetExceptionKind: TDbgTargetExceptionKind;
begin
  Result := tekUnknown;
end;

function TDbgTargetExceptionInfoTemplate.GetExceptionMessage(out AMessage: String): boolean;
begin
  AMessage := '';
  Result := False;
end;

function TDbgTargetExceptionInfoTemplate.GetExceptionRaiseAtFrameAddr(out AFrameAddr: TDBGPtr
  ): boolean;
begin
  AFrameAddr := 0;
  Result := False;
end;

function TDbgTargetExceptionInfoTemplate.GetExceptionBaseClassName(out AClassName: String;
  AnIndex: integer): boolean;
begin
  AClassName := '';
  Result := False;
end;

{ TDbgExceptionHandlerListTemplate }

function TDbgExceptionHandlerListTemplate.GetIgnoreAllExceptions: Boolean;
begin
  Result := False;
end;

function TDbgExceptionHandlerListTemplate.FindExceptionHandler(
  const AnExceptTargetInfo: IDbgTargetExceptionInfo): IDbgExceptionHandler;
begin
  Result := nil;
end;

function TDbgExceptionHandlerListTemplate.Find(const AClassName: String): IDbgExceptionHandler;
begin
  Result := nil;
end;

end.

